version: '3'
services:
  crawler:
    build: ./crawler
    depends_on:
      - elastic_consumer
      - nats
      - proxy
    volumes:
      - ./data_store:/usr/share/data
  elastic_consumer:
    build: ./elastic_consumer
    depends_on:
      elastic:
        condition: service_healthy
    volumes:
      - ./data_store:/usr/share/data
  api:
    build: ./api
    depends_on:
      - elastic_facade
    expose:
      - '8080'
  elastic_facade:
    build: ./elastic_facade
    environment:
      - ELASTICSEARCH_USER=elastic
      - ELASTICSEARCH_PASSWORD=password
    depends_on:
      elastic:
        condition: service_healthy
    expose:
      - '8080'
  proxy:
    build:
      context: ./server/
      dockerfile: server.dockerfile
    depends_on:
      - api
    ports:
      - '4000:4000'
      - '4001:80'
      - '4002:8080'
    volumes:
      - ./data_store:/usr/share/data
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: es01
    depends_on:
      - nats
    environment:
      - node.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elastic:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'curl --silent --fail localhost:9200/_cluster/health?wait_for_status=green&timeout=1s || exit 1',
        ]
      interval: 30s
      timeout: 30s
      retries: 3
  nats:
    image: nats:latest
    ports:
      - '4222:4222'

networks:
  k6:
  grafana:

volumes:
  data01:
    driver: local
