version: "3"
services:
  api:
    build: ./api
    depends_on:
      - elastic_facade
    expose:
      - "8080"
  elastic_facade:
    build: ./elastic_facade
    environment:
      - ELASTICSEARCH_USER=elastic
      - ELASTICSEARCH_PASSWORD=changeme
    depends_on:
      elastic:
        condition: service_healthy
    expose:
      - "8080"
  proxy:
    build:
      context : ./server/
      dockerfile: server.dockerfile
    depends_on:
      - api
    ports:
      - "4000:4000"
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: es01
    environment:
      - node.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elastic:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health?wait_for_status=green&timeout=1s || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
  nats:
    image: nats:latest
    ports:
      - "4222:4222"

volumes:
  data01:
    driver: local